# SPDX-License-Identifier: Apache-2.0
"""Meridian V1 Evidence Catalog, audit, lineage, and OTel bridge contracts."""

from ._version import __version__
from .catalogs import (
    EVIDENCE_CONTRACT_VERSION,
    EVIDENCE_REGISTRY_REF,
    EvidenceCatalogProvider,
    EvidenceCatalogSurface,
    PolicyResolver,
    evidence_manifest,
)
from .errors import (
    EVIDENCE_ERROR_CODES,
    EvidenceCapabilityMismatch,
    EvidenceErrorCode,
    EvidenceIdempotencyConflict,
    EvidencePolicyViolation,
    EvidenceQueueExhausted,
    EvidenceScopeViolation,
    InvalidAuditCorrection,
    InvalidEvidenceDefinition,
    InvalidEvidenceRecord,
    LineageCheckpointIncomplete,
)
from .hooks import EvidenceHookPlan, HookFailureAction, OperationEvidenceHooks
from .otel import OTelBridgeHealth, OTelEvidenceBridge, OTelRecord
from .policy import (
    AtomicityPolicy,
    CardinalityBudget,
    EvidencePolicy,
    PolicyDecision,
    QueueFailurePolicy,
    RedactionRule,
    RedactionStrategy,
    RetentionPolicyInput,
)
from .query import EvidenceQuery, EvidenceQueryResult, QueryDirection, QueryOrder
from .records import (
    EVIDENCE_DATA_FORMAT_VERSION,
    AuditOutcome,
    AuditRecord,
    Correlation,
    EvidenceMetadata,
    EvidenceProfile,
    EvidenceRecord,
    EvidenceReference,
    LineageRecord,
    LineageStatus,
    LogRecord,
    MetricPoint,
    MetricTemporality,
    ProvenanceRecord,
    SpanRecord,
    deterministic_evidence_id,
    record_mapping,
)
from .schemas import EvidenceSchemaProvider, evidence_schema, schema_names

__all__ = [
    "EVIDENCE_CONTRACT_VERSION",
    "EVIDENCE_DATA_FORMAT_VERSION",
    "EVIDENCE_ERROR_CODES",
    "EVIDENCE_REGISTRY_REF",
    "AtomicityPolicy",
    "AuditOutcome",
    "AuditRecord",
    "CardinalityBudget",
    "Correlation",
    "EvidenceCapabilityMismatch",
    "EvidenceCatalogProvider",
    "EvidenceCatalogSurface",
    "EvidenceErrorCode",
    "EvidenceHookPlan",
    "EvidenceIdempotencyConflict",
    "EvidenceMetadata",
    "EvidencePolicy",
    "EvidencePolicyViolation",
    "EvidenceProfile",
    "EvidenceQuery",
    "EvidenceQueryResult",
    "EvidenceQueueExhausted",
    "EvidenceRecord",
    "EvidenceReference",
    "EvidenceSchemaProvider",
    "EvidenceScopeViolation",
    "HookFailureAction",
    "InvalidAuditCorrection",
    "InvalidEvidenceDefinition",
    "InvalidEvidenceRecord",
    "LineageCheckpointIncomplete",
    "LineageRecord",
    "LineageStatus",
    "LogRecord",
    "MetricPoint",
    "MetricTemporality",
    "OTelBridgeHealth",
    "OTelEvidenceBridge",
    "OTelRecord",
    "OperationEvidenceHooks",
    "PolicyDecision",
    "PolicyResolver",
    "ProvenanceRecord",
    "QueryDirection",
    "QueryOrder",
    "QueueFailurePolicy",
    "RedactionRule",
    "RedactionStrategy",
    "RetentionPolicyInput",
    "SpanRecord",
    "__version__",
    "deterministic_evidence_id",
    "evidence_manifest",
    "evidence_schema",
    "record_mapping",
    "schema_names",
]
